### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by Trevor159** [chestnut1693/batslocator#1]
People have reported in discord that this plugin does not work. Have you tested this/are you aware of this?

**Comment by Trevor159** [comment]
It turns out this is probably because they people complaining did not realize that the plugin is disabled by default (which it probably shouldn't be)

**Comment by chestnut1693** [comment]
I prefer not having plugins enabled by default just as not having new features of plugins enabled by default. You want this to be changed?

**Comment by Trevor159** [comment]
> I prefer not having plugins enabled by default just as not having new features of plugins enabled by default. You want this to be changed?

there is basically no point for external plugins do default to off. The user has to install it manually which is basically the same thing as turning it on. If you default it to off then the user has to install it and then turn it on which is less intuitive.
