### ISSUE TITLE
The plugin does not show any indicators on the chests

### ISSUE THREAD

**Issue by JeljoGb** [chestnut1693/batslocator#2]
I installed the plugin, it's turned on, I didn't change any settings, yet I don't see any indicators on any thieving chests in cox.
I'm willing to do any troubleshooting you throw at me. So far I've uninstalled and reinstalled the plugin multiple times, turned it on and off, nothing does anything.

**Comment by chestnut1693** [comment]
It's hard for me to do any diagnosis without begin able to see what is happening. During development I've encountered many problems and I resolved them along the way with the use of breakpoints which I can't use now. One thing you could try is turning the plugin on and off while standing in the center of the thieving room. This will make sure all the chest and trough objects have spawned. Do you happen to know in which room it happened and what the rotation of the room was? A screenshot would be helpful. This plugin has not been tested in challenge mode.

**Comment by JeljoGb** [comment]
Thanks for the reply, I'll test it out today, and report back with screenshots.

**Comment by JeljoGb** [comment]
With plugin not installed
![image](https://user-images.githubusercontent.com/34870401/73812123-00cc7d00-47dc-11ea-9795-2a5b61bed985.png)
With plugin installed and turned on
![image](https://user-images.githubusercontent.com/34870401/73812165-31acb200-47dc-11ea-81d9-562d3ab2bfe1.png)
Turning it off and on
![image](https://user-images.githubusercontent.com/34870401/73812174-3b361a00-47dc-11ea-8524-05ea3d87a3ab.png)
![image](https://user-images.githubusercontent.com/34870401/73812177-42f5be80-47dc-11ea-9ea8-78af48b8a10b.png)
Changing random settings
![image](https://user-images.githubusercontent.com/34870401/73812199-586ae880-47dc-11ea-8cc3-92b851412274.png)
With a chest opened
![image](https://user-images.githubusercontent.com/34870401/73812214-63257d80-47dc-11ea-86c3-c9fb93b5a5a1.png)

It happens in all rooms, I just can't get it to work.

**Comment by chestnut1693** [comment]
I really can't say. The dots will be drawn when the amount of chests spawned is equal to the amount I have set it to. It doesn't seem that the amount of chests has changed so it must be in the part that draws the dots. I know that the part that draws the dots stops drawing when null pointer exceptions are thrown. So I'm guessing something is throwing a null pointer exception.

The only way I know of to detect this is by running runelite through an IDE in debugging mode or by running a self compiled runelite through the ``java`` program.

**Comment by Ktownstoner** [comment]
Same problem here also tried un-installing and resetting and nothing at all seems to work

**Comment by imphatty** [comment]
Also having this issue, along with a couple friends of mine.  Tried on/off, uninstall/reinstall.. still getting zero indicators in thieving room, multiple different layouts.  Anything i can send to help figure this issue out? thanks.

**Comment by Makendu-OSRS** [comment]
has never worked for me or any of my mates on mac

**Comment by chestnut1693** [comment]
@JeljoGb @Ktownstoner @imphatty @Makendu-OSRS
I might be able to locate the problem by looking in your log files. Could you post your most recent logfile here or send it to me the next time you are in the thieving room?

**Comment by imphatty** [comment]
I definitely will.. could you tell me how to get to the log file? >.< 
thanks

**Comment by chestnut1693** [comment]
On windows the log folder is located at C:\Users\User\\.runelite\logs. In here there are multiple log files and the one called client.log is the most recent.

**Comment by chestnut1693** [comment]
Someone has showed me their log and there wasn't anything unusual which is quite depressing. It could be that the person made a mistake and showed the wrong log but I doubt it. The problem is not a null pointer exception as far as I can tell.

**Comment by JeljoGb** [comment]
I'll try getting my log.

**Comment by JeljoGb** [comment]
Oh shit
I turned on the gpu plugin and now it works. I turned off the gpu plugin and it still works.

**Comment by JeljoGb** [comment]
@Ktownstoner @imphatty @Makendu-OSRS try my previous message

**Comment by chestnut1693** [comment]
The issue has been discovered. The bats locator plugin uses `.getDrawDistance()` to determine if the player is close enough for the dots to be drawn. But `.getDrawDistance()` returns 0 if the gpu plugin hasn't been enabled. An [issue](https://github.com/runelite/runelite/issues/11247) over at the runelite repository has been created to resolve this. I will make the change here if it doesn't get resolved. In the mean time enable the gpu plugin once or keep it enabled. Thanks @JeljoGb.
